# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Palapa
                                 A QGIS plugin
 Plugin yang berguna untuk mengupload data spasial, style, dan metadata ke Geoportal Palapa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-27
        copyright            : (C) 2021 by BIG
        email                : sandysetyanagara@mail.ugm.ac.id
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Palapa class from file Palapa.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Palapa import Palapa
    return Palapa(iface)
