# Form implementation generated from reading ui file 'c:\Users\lenovo\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Plugin-upload-Palapa\ui\publish_layer.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_publish_layer(object):
    def setupUi(self, publish_layer):
        publish_layer.setObjectName("publish_layer")
        publish_layer.resize(400, 114)
        self.verticalLayout = QtWidgets.QVBoxLayout(publish_layer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_layer = QtWidgets.QLabel(publish_layer)
        self.label_layer.setObjectName("label_layer")
        self.verticalLayout.addWidget(self.label_layer)
        self.label_2 = QtWidgets.QLabel(publish_layer)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cmb_download = QtWidgets.QComboBox(publish_layer)
        self.cmb_download.setObjectName("cmb_download")
        self.verticalLayout.addWidget(self.cmb_download)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_tutup = QtWidgets.QPushButton(publish_layer)
        self.pushButton_tutup.setObjectName("pushButton_tutup")
        self.horizontalLayout.addWidget(self.pushButton_tutup)
        self.pushButton_proses = QtWidgets.QPushButton(publish_layer)
        self.pushButton_proses.setObjectName("pushButton_proses")
        self.horizontalLayout.addWidget(self.pushButton_proses)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(publish_layer)
        QtCore.QMetaObject.connectSlotsByName(publish_layer)

    def retranslateUi(self, publish_layer):
        _translate = QtCore.QCoreApplication.translate
        publish_layer.setWindowTitle(_translate("publish_layer", "Publish layer"))
        self.label_layer.setText(_translate("publish_layer", "Anda akan mempublish layer"))
        self.label_2.setText(_translate("publish_layer", "Aktifkan Pengunduhan untuk layer ini?"))
        self.pushButton_tutup.setText(_translate("publish_layer", "Tutup"))
        self.pushButton_proses.setText(_translate("publish_layer", "Proses!"))
